# Generated by Django 5.1.15 on 2025-12-17 20:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_add_agent_to_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativado, o chatbot pode processar pagamentos', verbose_name='Aceita Pagamentos')),
                ('pix_key', models.CharField(blank=True, help_text='Sua chave PIX onde você receberá os pagamentos', max_length=100, verbose_name='Chave PIX para Recebimento')),
                ('pix_key_type', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('phone', 'Telefone'), ('evp', 'Chave Aleatória')], default='cpf', max_length=10, verbose_name='Tipo de Chave PIX')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Apenas números, 11 dígitos para CPF ou 14 para CNPJ', max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos ou CNPJ 14 dígitos (apenas números)', regex='^(\\d{11}|\\d{14})$')], verbose_name='CPF/CNPJ do Titular')),
                ('holder_name', models.CharField(blank=True, help_text='Nome completo conforme documento', max_length=200, verbose_name='Nome do Titular')),
                ('bank_code', models.CharField(blank=True, choices=[('001', '001 - Banco do Brasil'), ('033', '033 - Santander'), ('104', '104 - Caixa Econômica'), ('237', '237 - Bradesco'), ('341', '341 - Itaú'), ('756', '756 - Sicoob'), ('748', '748 - Sicredi'), ('077', '077 - Inter'), ('260', '260 - Nubank'), ('336', '336 - C6 Bank'), ('212', '212 - Original'), ('422', '422 - Safra'), ('655', '655 - Votorantim'), ('745', '745 - Citibank'), ('041', '041 - Banrisul'), ('070', '070 - BRB'), ('085', '085 - AILOS'), ('136', '136 - Unicred'), ('389', '389 - Mercantil do Brasil'), ('707', '707 - Daycoval'), ('218', '218 - BS2'), ('380', '380 - PicPay Servicos'), ('290', '290 - PagSeguro'), ('323', '323 - Mercado Pago'), ('364', '364 - Efí Bank')], max_length=3, verbose_name='Banco')),
                ('agency', models.CharField(blank=True, help_text='Número da agência (sem dígito)', max_length=10, verbose_name='Agência')),
                ('account', models.CharField(blank=True, help_text='Número da conta', max_length=15, verbose_name='Conta')),
                ('account_digit', models.CharField(blank=True, help_text='Dígito verificador da conta', max_length=2, verbose_name='Dígito')),
                ('account_type', models.CharField(choices=[('CONTA_CORRENTE', 'Conta Corrente'), ('CONTA_POUPANCA', 'Conta Poupança')], default='CONTA_CORRENTE', max_length=20, verbose_name='Tipo de Conta')),
                ('pix_enabled', models.BooleanField(default=True, verbose_name='PIX Habilitado')),
                ('boleto_enabled', models.BooleanField(default=False, verbose_name='Boleto Habilitado')),
                ('credit_card_enabled', models.BooleanField(default=False, verbose_name='Cartão de Crédito Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('padaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento',
                'verbose_name_plural': 'Configurações de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(help_text='Identificador único da transação PIX', max_length=100, unique=True, verbose_name='TXID do PIX')),
                ('external_reference', models.CharField(blank=True, help_text='ID do pedido/sessão no chatbot', max_length=200, verbose_name='Referência Externa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('billing_type', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão de Crédito')], default='PIX', max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('RECEIVED', 'Recebido'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Estornado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Cliente')),
                ('customer_email', models.CharField(blank=True, max_length=100, verbose_name='E-mail do Cliente')),
                ('pix_qrcode', models.TextField(blank=True, verbose_name='QR Code PIX (base64)')),
                ('pix_copy_paste', models.TextField(blank=True, verbose_name='PIX Copia e Cola')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentconfig', verbose_name='Configuração de Pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
