# Generated by Django 5.1.15 on 2025-12-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_agent_to_apikey'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentconfig',
            name='padaria',
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='ID da Sessão Stripe')),
                ('checkout_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Checkout')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Cliente')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Cliente')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Pedido')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('expired', 'Expirado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('padaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Sessão de Pagamento',
                'verbose_name_plural': 'Sessões de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID da Conta Stripe')),
                ('is_onboarding_complete', models.BooleanField(default=False, verbose_name='Onboarding Completo')),
                ('charges_enabled', models.BooleanField(default=False, verbose_name='Pode Receber Pagamentos')),
                ('payouts_enabled', models.BooleanField(default=False, verbose_name='Pode Receber Transferências')),
                ('details_submitted', models.BooleanField(default=False, verbose_name='Dados Enviados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('padaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_account', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Conta Stripe',
                'verbose_name_plural': 'Contas Stripe',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentConfig',
        ),
    ]
