# Generated by Django 5.1.11 on 2026-01-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_dynamic_image_paths'),
        ('payments', '0002_remove_paymentconfig_padaria_paymentsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_customer_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID do Cliente no Asaas')),
                ('asaas_subscription_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID da Assinatura no Asaas')),
                ('plan_name', models.CharField(default='Plano Único', max_length=100, verbose_name='Nome do Plano')),
                ('plan_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Plano (R$)')),
                ('billing_type', models.CharField(choices=[('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('BOLETO', 'Boleto')], default='PIX', max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('overdue', 'Inadimplente'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Status')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Último Pagamento')),
                ('current_payment_link', models.URLField(blank=True, max_length=500, verbose_name='Link de Pagamento Atual')),
                ('current_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID do Pagamento Atual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('padaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asaas_subscription', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Assinatura Asaas',
                'verbose_name_plural': 'Assinaturas Asaas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsaasPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_payment_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID do Pagamento no Asaas')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('billing_type', models.CharField(max_length=20, verbose_name='Forma de Pagamento')),
                ('invoice_url', models.URLField(blank=True, max_length=500, verbose_name='Link da Fatura')),
                ('pix_qrcode', models.TextField(blank=True, verbose_name='QR Code PIX (Base64)')),
                ('pix_copy_paste', models.TextField(blank=True, verbose_name='PIX Copia e Cola')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('received', 'Recebido'), ('overdue', 'Vencido'), ('refunded', 'Estornado'), ('deleted', 'Removido')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.asaassubscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento Asaas',
                'verbose_name_plural': 'Pagamentos Asaas',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, help_text='Token privado do Mercado Pago', max_length=200, verbose_name='Access Token')),
                ('public_key', models.CharField(blank=True, help_text='Chave pública do Mercado Pago', max_length=100, verbose_name='Public Key')),
                ('is_active', models.BooleanField(default=False, help_text='Credenciais verificadas e funcionando', verbose_name='Ativo')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('padaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercadopago_config', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Configuração Mercado Pago',
                'verbose_name_plural': 'Configurações Mercado Pago',
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID do Pagamento no MP')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Preferência no MP')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Pagador')),
                ('payer_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Pagador')),
                ('checkout_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Checkout')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('authorized', 'Autorizado'), ('in_process', 'Em Processamento'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.mercadopagoconfig', verbose_name='Configuração MP')),
            ],
            options={
                'verbose_name': 'Pagamento Mercado Pago',
                'verbose_name_plural': 'Pagamentos Mercado Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
