# Generated by Django 5.1.11 on 2026-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_asaas_mercadopago_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadopagopayment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='mercadopagopayment',
            name='pix_qr_code',
            field=models.TextField(blank=True, verbose_name='PIX Copia e Cola'),
        ),
        migrations.AddField(
            model_name='mercadopagopayment',
            name='pix_qr_code_base64',
            field=models.TextField(blank=True, verbose_name='QR Code PIX (base64)'),
        ),
        migrations.AddField(
            model_name='mercadopagopayment',
            name='ticket_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL do Ticket'),
        ),
    ]
