# Generated by Django 5.1.15 on 2026-02-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_socio_responsavel_fields'),
        ('payments', '0004_add_pix_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaktoSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.IntegerField(default=15, help_text='Quantidade de dias de uso gratuito', verbose_name='Dias de Trial')),
                ('trial_start_date', models.DateField(blank=True, null=True, verbose_name='Início do Trial')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='Fim do Trial')),
                ('cakto_offer_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Oferta Cakto')),
                ('cakto_order_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID do Pedido Cakto')),
                ('card_registered', models.BooleanField(default=False, verbose_name='Cartão Cadastrado')),
                ('card_last_4', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='Bandeira')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativa'), ('inactive', 'Inativa'), ('cancelled', 'Cancelada')], default='trial', max_length=20, verbose_name='Status')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima Cobrança')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Último Pagamento')),
                ('plan_name', models.CharField(default='Plano Mensal', max_length=100, verbose_name='Nome do Plano')),
                ('plan_value', models.DecimalField(decimal_places=2, default=140.0, max_digits=10, verbose_name='Valor do Plano (R$)')),
                ('checkout_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Checkout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('padaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cakto_subscription', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Assinatura Cakto',
                'verbose_name_plural': 'Assinaturas Cakto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaktoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakto_order_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID do Pedido Cakto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('billing_period_start', models.DateField(blank=True, null=True, verbose_name='Início do Período')),
                ('billing_period_end', models.DateField(blank=True, null=True, verbose_name='Fim do Período')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('refunded', 'Estornado')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.caktosubscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento Cakto',
                'verbose_name_plural': 'Pagamentos Cakto',
                'ordering': ['-created_at'],
            },
        ),
    ]
