# Generated by Django 5.1.15 on 2026-02-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_cakto_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='caktosubscription',
            name='cakto_subscription_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID da Assinatura Cakto'),
        ),
    ]
