# Generated by Django 5.1.15 on 2026-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_add_agent_to_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='afternoon_end',
            field=models.TimeField(blank=True, help_text='Ex: 17:00', null=True, verbose_name='Horário Final - Vespertino'),
        ),
        migrations.AddField(
            model_name='agent',
            name='afternoon_start',
            field=models.TimeField(blank=True, help_text='Ex: 13:00', null=True, verbose_name='Horário Inicial - Vespertino'),
        ),
        migrations.AddField(
            model_name='agent',
            name='morning_end',
            field=models.TimeField(blank=True, help_text='Ex: 11:00', null=True, verbose_name='Horário Final - Matutino'),
        ),
        migrations.AddField(
            model_name='agent',
            name='morning_start',
            field=models.TimeField(blank=True, help_text='Ex: 07:00', null=True, verbose_name='Horário Inicial - Matutino'),
        ),
        migrations.AddField(
            model_name='agent',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text="Lista de dias que funciona: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']", verbose_name='Dias de Funcionamento'),
        ),
    ]
