# Generated by Django 5.1.15 on 2025-12-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_promocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Campanha')),
                ('mensagem', models.TextField(help_text='Use {{nome_cliente}} para personalizar', verbose_name='Mensagem')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='campanhas/', verbose_name='Imagem (opcional)')),
                ('delay_minimo', models.IntegerField(default=10, help_text='Tempo mínimo entre cada mensagem', verbose_name='Delay mínimo (segundos)')),
                ('delay_maximo', models.IntegerField(default=30, help_text='Tempo máximo entre cada mensagem', verbose_name='Delay máximo (segundos)')),
                ('lote_tamanho', models.IntegerField(default=10, help_text='Quantidade de mensagens por lote antes de pausa maior', verbose_name='Tamanho do lote')),
                ('pausa_entre_lotes', models.IntegerField(default=60, help_text='Tempo de pausa após cada lote', verbose_name='Pausa entre lotes (segundos)')),
                ('data_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de agendamento')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('enviando', 'Em Envio'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='rascunho', max_length=20, verbose_name='Status')),
                ('total_destinatarios', models.IntegerField(default=0, verbose_name='Total de destinatários')),
                ('enviados', models.IntegerField(default=0, verbose_name='Enviados')),
                ('falhas', models.IntegerField(default=0, verbose_name='Falhas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('padaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='organizations.padaria', verbose_name='Padaria')),
                ('promocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas', to='organizations.promocao', verbose_name='Promoção vinculada')),
            ],
            options={
                'verbose_name': 'Campanha WhatsApp',
                'verbose_name_plural': 'Campanhas WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Número com DDD, ex: (11) 99999-9999', max_length=20, verbose_name='Telefone/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('aceita_promocoes', models.BooleanField(default=True, help_text='Cliente autoriza receber mensagens de promoções', verbose_name='Aceita receber promoções')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('padaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'unique_together': {('padaria', 'telefone')},
            },
        ),
        migrations.CreateModel(
            name='MensagemCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('falha', 'Falha')], default='pendente', max_length=20, verbose_name='Status')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='organizations.campanhawhatsapp', verbose_name='Campanha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='organizations.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Mensagem de Campanha',
                'verbose_name_plural': 'Mensagens de Campanha',
                'ordering': ['id'],
                'unique_together': {('campanha', 'cliente')},
            },
        ),
    ]
