# Generated by Django 5.1.11 on 2026-01-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Se vinculado, a promoção usará a imagem do produto quando não tiver imagem própria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes', to='organizations.produto', verbose_name='Produto vinculado'),
        ),
    ]
