# Generated by Django 5.1.11 on 2026-01-07 13:30

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_promocao_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhawhatsapp',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.get_campanha_upload_path, verbose_name='Imagem (opcional)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.get_produto_upload_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.get_promocao_upload_path, verbose_name='Imagem'),
        ),
    ]
