# Generated by Django 5.1.15 on 2026-02-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_dynamic_image_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='padaria',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do Responsável Pandia'),
        ),
        migrations.AddField(
            model_name='padaria',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Responsável Pandia'),
        ),
        migrations.AddField(
            model_name='padaria',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Responsável Pandia'),
        ),
        migrations.AddField(
            model_name='padaria',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável Pandia'),
        ),
        migrations.AddField(
            model_name='padaria',
            name='socio_cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do Sócio Administrador'),
        ),
        migrations.AddField(
            model_name='padaria',
            name='socio_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Sócio Administrador'),
        ),
    ]
