# Generated by Django 5.1.15 on 2026-01-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuário Padaria')], default='user', max_length=20, verbose_name='Papel no Sistema'),
        ),
    ]
