# Generated by Django 5.1.15 on 2026-01-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP do administrador (usado para região de atuação)', max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
