# Generated by Django 5.1.15 on 2026-02-05 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_cep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador do Sistema'), ('agente_credenciado', 'Agente Credenciado'), ('user', 'Usuário Padaria')], default='user', max_length=20, verbose_name='Papel no Sistema'),
        ),
        migrations.CreateModel(
            name='AgenteCredenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('regioes_atuacao', models.JSONField(blank=True, default=list, help_text='Lista de cidades/estados onde o agente pode atuar', verbose_name='Regiões de Atuação')),
                ('padarias_cadastradas_ids', models.JSONField(blank=True, default=list, help_text='IDs das padarias cadastradas por este agente', verbose_name='IDs das Padarias Cadastradas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente_credenciado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Agente Credenciado',
                'verbose_name_plural': 'Agentes Credenciados',
                'ordering': ['-created_at'],
            },
        ),
    ]
